In [36]:
import numpy as np
import pandas as pd
import scipy.stats as ss
import plotly.express as px
import seaborn as sns
from matplotlib import pyplot as plt
from feature_engine.imputation import MeanMedianImputer

In [37]:
data = pd.read_csv('data/weatherAUS.csv')
data

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN   
1       2008-12-02   Albury      7.4     25.1       0.0          NaN   
2       2008-12-03   Albury     12.9     25.7       0.0          NaN   
3       2008-12-04   Albury      9.2     28.0       0.0          NaN   
4       2008-12-05   Albury     17.5     32.3       1.0          NaN   
...            ...      ...      ...      ...       ...          ...   
145455  2017-06-21    Uluru      2.8     23.4       0.0          NaN   
145456  2017-06-22    Uluru      3.6     25.3       0.0          NaN   
145457  2017-06-23    Uluru      5.4     26.9       0.0          NaN   
145458  2017-06-24    Uluru      7.8     27.0       0.0          NaN   
145459  2017-06-25    Uluru     14.9      NaN       0.0          NaN   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  \
0            NaN           W           44.0          W  ...        71.0   
1            NaN         WNW           44.0        NNW  ...        44.0   
2            NaN         WSW           46.0          W  ...        38.0   
3            NaN          NE           24.0         SE  ...        45.0   
4            NaN           W           41.0        ENE  ...        82.0   
...          ...         ...            ...        ...  ...         ...   
145455       NaN           E           31.0         SE  ...        51.0   
145456       NaN         NNW           22.0         SE  ...        56.0   
145457       NaN           N           37.0         SE  ...        53.0   
145458       NaN          SE           28.0        SSE  ...        51.0   
145459       NaN         NaN            NaN        ESE  ...        62.0   

        Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  \
0              22.0       1007.7       1007.1       8.0       NaN     16.9   
1              25.0       1010.6       1007.8       NaN       NaN     17.2   
2              30.0       1007.6       1008.7       NaN       2.0     21.0   
3              16.0       1017.6       1012.8       NaN       NaN     18.1   
4              33.0       1010.8       1006.0       7.0       8.0     17.8   
...             ...          ...          ...       ...       ...      ...   
145455         24.0       1024.6       1020.3       NaN       NaN     10.1   
145456         21.0       1023.5       1019.1       NaN       NaN     10.9   
145457         24.0       1021.0       1016.8       NaN       NaN     12.5   
145458         24.0       1019.4       1016.5       3.0       2.0     15.1   
145459         36.0       1020.2       1017.9       8.0       8.0     15.0   

        Temp3pm  RainToday  RainTomorrow  
0          21.8         No            No  
1          24.3         No            No  
2          23.2         No            No  
3          26.5         No            No  
4          29.7         No            No  
...         ...        ...           ...  
145455     22.4         No            No  
145456     24.5         No            No  
145457     26.1         No            No  
145458     26.0         No            No  
145459     20.9         No           NaN  

[145460 rows x 23 columns]

In [38]:
data['Date'] = pd.to_datetime(data['Date'])
data.set_index('Date', inplace=True)
data

Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
Date                                                                     
2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   
...             ...      ...      ...       ...          ...       ...   
2017-06-21    Uluru      2.8     23.4       0.0          NaN       NaN   
2017-06-22    Uluru      3.6     25.3       0.0          NaN       NaN   
2017-06-23    Uluru      5.4     26.9       0.0          NaN       NaN   
2017-06-24    Uluru      7.8     27.0       0.0          NaN       NaN   
2017-06-25    Uluru     14.9      NaN       0.0          NaN       NaN   

           WindGustDir  WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  \
Date                                                         ...                
2008-12-01           W           44.0          W        WNW  ...         71.0   
2008-12-02         WNW           44.0        NNW        WSW  ...         44.0   
2008-12-03         WSW           46.0          W        WSW  ...         38.0   
2008-12-04          NE           24.0         SE          E  ...         45.0   
2008-12-05           W           41.0        ENE         NW  ...         82.0   
...                ...            ...        ...        ...  ...          ...   
2017-06-21           E           31.0         SE        ENE  ...         51.0   
2017-06-22         NNW           22.0         SE          N  ...         56.0   
2017-06-23           N           37.0         SE        WNW  ...         53.0   
2017-06-24          SE           28.0        SSE          N  ...         51.0   
2017-06-25         NaN            NaN        ESE        ESE  ...         62.0   

            Humidity3pm  Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  \
Date                                                                    
2008-12-01         22.0       1007.7       1007.1       8.0       NaN   
2008-12-02         25.0       1010.6       1007.8       NaN       NaN   
2008-12-03         30.0       1007.6       1008.7       NaN       2.0   
2008-12-04         16.0       1017.6       1012.8       NaN       NaN   
2008-12-05         33.0       1010.8       1006.0       7.0       8.0   
...                 ...          ...          ...       ...       ...   
2017-06-21         24.0       1024.6       1020.3       NaN       NaN   
2017-06-22         21.0       1023.5       1019.1       NaN       NaN   
2017-06-23         24.0       1021.0       1016.8       NaN       NaN   
2017-06-24         24.0       1019.4       1016.5       3.0       2.0   
2017-06-25         36.0       1020.2       1017.9       8.0       8.0   

            Temp9am  Temp3pm  RainToday  RainTomorrow  
Date                                                   
2008-12-01     16.9     21.8         No            No  
2008-12-02     17.2     24.3         No            No  
2008-12-03     21.0     23.2         No            No  
2008-12-04     18.1     26.5         No            No  
2008-12-05     17.8     29.7         No            No  
...             ...      ...        ...           ...  
2017-06-21     10.1     22.4         No            No  
2017-06-22     10.9     24.5         No            No  
2017-06-23     12.5     26.1         No            No  
2017-06-24     15.1     26.0         No            No  
2017-06-25     15.0     20.9         No           NaN  

[145460 rows x 22 columns]

In [39]:
mean_filler = MeanMedianImputer(variables=data.select_dtypes(include=np.number).columns.tolist())
mean_filler.fit(data)
data = mean_filler.transform(data)
data.isna().sum()

Location             0
MinTemp              0
MaxTemp              0
Rainfall             0
Evaporation          0
Sunshine             0
WindGustDir      10326
WindGustSpeed        0
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am         0
WindSpeed3pm         0
Humidity9am          0
Humidity3pm          0
Pressure9am          0
Pressure3pm          0
Cloud9am             0
Cloud3pm             0
Temp9am              0
Temp3pm              0
RainToday         3261
RainTomorrow      3267
dtype: int64

## Identify data types and measurement levels of dataset

In [40]:
numerical = data.select_dtypes(include=np.number)
categorical = data.select_dtypes(include=np.object)

In [41]:
numerical.head(5).T

Date           2008-12-01  2008-12-02  2008-12-03  2008-12-04  2008-12-05
MinTemp              13.4         7.4        12.9         9.2        17.5
MaxTemp              22.9        25.1        25.7        28.0        32.3
Rainfall              0.6         0.0         0.0         0.0         1.0
Evaporation           4.8         4.8         4.8         4.8         4.8
Sunshine              8.4         8.4         8.4         8.4         8.4
WindGustSpeed        44.0        44.0        46.0        24.0        41.0
WindSpeed9am         20.0         4.0        19.0        11.0         7.0
WindSpeed3pm         24.0        22.0        26.0         9.0        20.0
Humidity9am          71.0        44.0        38.0        45.0        82.0
Humidity3pm          22.0        25.0        30.0        16.0        33.0
Pressure9am        1007.7      1010.6      1007.6      1017.6      1010.8
Pressure3pm        1007.1      1007.8      1008.7      1012.8      1006.0
Cloud9am              8.0         5.0         5.0         5.0         7.0
Cloud3pm              5.0         5.0         2.0         5.0         8.0
Temp9am              16.9        17.2        21.0        18.1        17.8
Temp3pm              21.8        24.3        23.2        26.5        29.7

In [42]:
categorical.head(5).T

Date         2008-12-01 2008-12-02 2008-12-03 2008-12-04 2008-12-05
Location         Albury     Albury     Albury     Albury     Albury
WindGustDir           W        WNW        WSW         NE          W
WindDir9am            W        NNW          W         SE        ENE
WindDir3pm          WNW        WSW        WSW          E         NW
RainToday            No         No         No         No         No
RainTomorrow         No         No         No         No         No

In [43]:
numerical.nunique()

MinTemp          389
MaxTemp          505
Rainfall         681
Evaporation      358
Sunshine         145
WindGustSpeed     67
WindSpeed9am      43
WindSpeed3pm      44
Humidity9am      101
Humidity3pm      101
Pressure9am      546
Pressure3pm      549
Cloud9am          10
Cloud3pm          10
Temp9am          441
Temp3pm          502
dtype: int64

In [44]:
numerical['Evaporation'].unique()

array([4.80e+00, 1.20e+01, 1.48e+01, 1.26e+01, 1.08e+01, 1.14e+01,
       1.12e+01, 1.30e+01, 9.80e+00, 1.46e+01, 1.10e+01, 1.28e+01,
       1.38e+01, 1.64e+01, 1.74e+01, 1.60e+01, 1.36e+01, 8.00e+00,
       8.20e+00, 8.60e+00, 1.42e+01, 1.58e+01, 1.62e+01, 1.34e+01,
       1.44e+01, 1.18e+01, 1.56e+01, 1.52e+01, 1.16e+01, 9.60e+00,
       6.60e+00, 6.00e-01, 6.00e+00, 3.00e+00, 2.00e+00, 5.20e+00,
       9.00e+00, 1.02e+01, 1.00e+01, 7.40e+00, 8.40e+00, 9.20e+00,
       9.40e+00, 1.24e+01, 1.04e+01, 7.20e+00, 6.80e+00, 7.60e+00,
       4.40e+00, 6.40e+00, 7.80e+00, 7.00e+00, 8.80e+00, 6.20e+00,
       5.80e+00, 2.00e-01, 2.40e+00, 1.80e+00, 2.20e+00, 2.80e+00,
       5.00e+00, 5.60e+00, 4.20e+00, 4.00e+00, 3.20e+00, 4.60e+00,
       3.40e+00, 3.60e+00, 0.00e+00, 1.40e+00, 3.80e+00, 8.00e-01,
       2.60e+00, 1.60e+00, 1.20e+00, 1.00e+00, 5.40e+00, 1.06e+01,
       1.68e+01, 1.70e+01, 2.02e+01, 1.40e+01, 1.72e+01, 1.22e+01,
       1.50e+01, 1.82e+01, 1.32e+01, 4.10e+00, 1.70e+00, 4.00e

In [45]:
numerical['Sunshine'].unique()

array([ 8.4, 12.3, 13. , 13.3, 10.6, 12.2,  0. , 12.6, 13.2, 12.7, 12.1,
       10.3, 13.1, 12.9, 11.3,  6.9, 10.9,  3.7,  5.9, 10.5, 12.4, 13.4,
       13.6,  7.4, 10. ,  2.3,  6.6,  0.3, 10.7, 11.6, 10.2,  9. , 12. ,
        3. ,  7.9, 11.5, 11.2,  4.8,  5.8,  6. , 11.1, 11.8, 11.4, 10.8,
        7.8, 11. ,  5.5,  4.7,  4.2,  4.4,  6.2,  9.8,  9.9,  4.3,  8. ,
        9.6, 10.4,  9.3,  8.7,  7.6,  7.5, 10.1,  6.3,  2.8,  0.7,  9.4,
        9.7,  0.6,  5.1,  8.3,  4.1,  3.9,  6.8,  8.6,  2.7,  8.2,  3.1,
        1.8,  0.1,  0.8,  3.4,  7.1,  5. ,  5.7,  6.1,  7. ,  2.9,  2.5,
        4.6,  8.9,  9.1,  1.7,  8.1,  9.5,  1.2,  1.4,  8.8,  2.2,  3.5,
        9.2,  1.9, 11.7, 11.9,  7.7,  0.9, 12.5,  2.1, 12.8, 13.7,  8.5,
        0.2,  4. ,  2.4,  5.2,  0.5,  6.4,  4.5,  1.1,  2. ,  0.4,  1.5,
        3.3,  6.5,  2.6,  3.8,  3.6,  3.2,  6.7,  5.4,  7.2,  4.9,  1. ,
        1.6,  5.3,  7.3,  5.6,  1.3, 13.8, 13.5, 14. , 13.9, 14.1, 14.5,
       14.3, 14.2])

In [46]:
numerical['Cloud3pm'].unique()

array([5., 2., 8., 7., 1., 4., 6., 3., 0., 9.])

## measurement levels of features

### nominal scale
* location
* windGustDir
* windDir9am, windDir3pm
* rainToday, rainTomorrow

### continues scale

- possible interval level features
   * min/ max temperature
   * temp9am and temp3pm
   * date

- possible ratio level features
    * rainfall
    * wind speed
    * humidity
    * pressure
    * evaporation
    * sunshine

### discrete scale
* cloud9am
* cloude3pm

## EDA

### central tendency (3M)

In [47]:
# mean
np.mean(numerical)

MinTemp            12.192053
MaxTemp            23.215962
Rainfall            2.307990
Evaporation         5.179779
Sunshine            7.989889
WindGustSpeed      39.962189
WindSpeed9am       14.030751
WindSpeed3pm       18.669758
Humidity9am        68.901251
Humidity3pm        51.553396
Pressure9am      1017.644768
Pressure3pm      1015.250115
Cloud9am            4.659755
Cloud3pm            4.709913
Temp9am            16.987101
Temp3pm            21.668916
dtype: float64

In [48]:
# median
np.median(numerical, axis=0)

array([  12. ,   22.6,    0. ,    4.8,    8.4,   39. ,   13. ,   19. ,
         70. ,   52. , 1017.6, 1015.2,    5. ,    5. ,   16.7,   21.1])

In [49]:
ss.mode(numerical)

ModeResult(mode=array([[  12. ,   22.6,    0. ,    4.8,    8.4,   39. ,   13. ,   19. ,
          70. ,   52. , 1017.6, 1015.2,    5. ,    5. ,   16.7,   21.1]]), count=array([[ 2351,  1998, 94341, 64444, 70552, 19057, 14899, 14325,  5680,
         7258, 15818, 15771, 61455, 66173,  2575,  4338]]))

In [50]:
df = pd.DataFrame(data=[np.mean(numerical)])
df.loc[1,:] = np.median(numerical, axis=0)
df.loc[2,:] = ss.mode(numerical)[0][0]
df.T

0       1       2
MinTemp          12.192053    12.0    12.0
MaxTemp          23.215962    22.6    22.6
Rainfall          2.307990     0.0     0.0
Evaporation       5.179779     4.8     4.8
Sunshine          7.989889     8.4     8.4
WindGustSpeed    39.962189    39.0    39.0
WindSpeed9am     14.030751    13.0    13.0
WindSpeed3pm     18.669758    19.0    19.0
Humidity9am      68.901251    70.0    70.0
Humidity3pm      51.553396    52.0    52.0
Pressure9am    1017.644768  1017.6  1017.6
Pressure3pm    1015.250115  1015.2  1015.2
Cloud9am          4.659755     5.0     5.0
Cloud3pm          4.709913     5.0     5.0
Temp9am          16.987101    16.7    16.7
Temp3pm          21.668916    21.1    21.1

In [51]:
fig, axes = plt.subplots(nrows=8, ncols=2, figsize=[24, 48], dpi=300)
axes = axes.ravel()
cols = numerical.columns

for i in range(len(axes)):
    sns.histplot(x=numerical[cols[i]], ax=axes[i])

plt.savefig('graphs/un-engineered_dist.jpg')
plt.show()